create table e_upms_menu (
    id bigint generated by default as identity primary key,
    create_by varchar(255),
    create_time timestamp,
    update_by varchar(255),
    update_time timestamp,
    code varchar(255),
    icon varchar(255),
    name varchar(255),
    param varchar(255),
    sort integer,
    status integer,
    type varchar(255),
    value varchar(255),
    parent_menu_id bigint
);
